
package com.product.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductInterface", targetNamespace = "http://jaxb.soap.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductInterface {


    /**
     * 
     * @return
     *     returns com.soap.jaxb.Product
     */
    @WebMethod
    @WebResult(name = "Product", partName = "Product")
    public Product getProduct();

}
